
services:
  nginx:
    build: https://github.com/amazingplum53/portfolio.git#main:nginx
    hostname: matthewhill.click
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - challenge:/certbot-challenge
      - conf:/letsencrypt
      - static:/var/www/static
  certbot:
    image: certbot/certbot
    volumes:
      - challenge:/var/www/certbot
      - conf:/etc/letsencrypt
  gunicorn:
    build: https://github.com/amazingplum53/portfolio.git#main:gunicorn
    ports:
      - "8000:8000"
    volumes:
      - static:/var/www/portfolio/static
secrets:
  env:
    file: portfolio.env