FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

RUN apt update 

RUN apt-get update

ENV BASEDIR="/var/www" 

RUN apt-get -y install git python3-pip jq dnsutils curl unzip

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

RUN mkdir $BASEDIR/

RUN git clone https://github.com/amazingplum53/portfolio.git $BASEDIR/portfolio

WORKDIR $BASEDIR/portfolio

# Configure secrets

ARG settings=local

RUN mkdir ~/.aws

RUN echo "[default]" > ~/.aws/credentials

#RUN --mount=type=secret,id=env,dst=$BASEDIR/portfolio 

RUN mkdir /test/ /run/secrets/ /run/secrets/env/

COPY ./../portfolio.env /test/secrets/env/

RUN ln -s /test/secrets/env/portfolio.env $BASEDIR/portfolio/
    
RUN cat /test/secrets/env/portfolio.env | jq "aws_access_key_id=.aws_access_key_id \n aws_secret_access_key=.aws_secret_access_key" >> /root/.aws/credentials

RUN aws configure

# Configure Project


RUN python3 -m pip install -r portfolio/gunicorn/requirements.txt

ENV RUN_COMMAND="gunicorn portfolio.wsgi --chdir $BASEDIR/portfolio -c $BASEDIR/portfolio/gunicorn/gunicorn.config.py"

RUN echo 'alias run="$RUN_COMMAND"' >> ~/.bashrc

EXPOSE 8000

ENTRYPOINT ["bash", "-c"]

CMD ["$RUN_COMMAND"]
