apiVersion: apps/v1
kind: Deployment
metadata:
  name: gunicorn
  labels: 
    app: gunicorn
spec:
  selector:
    matchLabels:
      app: gunicorn
  template:
    metadata:
      labels:
        app: gunicorn
    spec:
      serviceAccountName: readonly
      containers:
      - name: gunicorn
        image: amazingplum/gunicorn-portfolio:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          protocol: TCP
        volumeMounts:
        - name: secret
          mountPath: /var/secrets/environ
      volumes:
      - name: secret
        secret:
          secretName: env-file

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gunicorn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gunicorn
  minReplicas: 0  # Scale down to zero replicas
  maxReplicas: 2  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale based on CPU utilization

