FROM ubuntu:latest

RUN apt update 

RUN apt-get update

ENV BASEDIR="/var/www" 

RUN apt-get -y install git

RUN git clone https://github.com/amazingplum53/portfolio.git portfolio


# Configure Nginx

RUN apt-get -y install nginx curl gnupg2 ca-certificates lsb-release ubuntu-keyring 

RUN curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

WORKDIR /etc/nginx/

RUN unlink sites-enabled/default

RUN unlink nginx.conf

RUN ln -s $BASEDIR/portfolio/conf/nginx.conf ./

RUN mkdir /data/ /data/certificates/ /data/certificates/portfolio/


# Configure Project

RUN mkdir $BASEDIR/

WORKDIR $BASEDIR

RUN apt-get -y install python3-pip python3.10-venv python3-dev libpq-dev systemctl

RUN python3 -m venv $BASEDIR/venv

RUN venv/bin/python3 -m pip install -r portfolio/conf/requirements.txt

ENV RUN_COMMAND="$BASEDIR/venv/bin/gunicorn portfolio.wsgi --chdir $BASEDIR/portfolio -c $BASEDIR/portfolio/conf/gunicorn.config.py"

RUN echo 'alias run="$RUN_COMMAND"' >> ~/.bashrc

EXPOSE 443 80

WORKDIR $BASEDIR/portfolio

COPY portfolio.env conf/

ENTRYPOINT ["bash", "-c"]

CMD ["$RUN_COMMAND"]
