# Generated by Django 4.0.3 on 2024-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_remove_article_content_image_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='order',
            new_name='position',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
