# Generated by Django 4.0.3 on 2024-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_order_image_position_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
