FROM nginx

#RUN apk update
#RUN apk add openssl

# Configure Nginx

WORKDIR /etc/nginx/

COPY nginx.conf ./

COPY openssl.cnf ./

RUN mkdir /letsencrypt/ /letsencrypt/live/ /letsencrypt/live/matthewhill.click/ 

RUN /usr/bin/openssl req -x509 -newkey rsa:4096 \
    -keyout /letsencrypt/live/matthewhill.click/privkey.pem \
    -out /letsencrypt/live/matthewhill.click/fullchain.pem \
    -sha256 -days 365 -config openssl.cnf -nodes


