FROM nginx

#RUN apk update
#RUN apk add openssl

# Configure Nginx

WORKDIR /etc/nginx/

COPY nginx.conf ./

COPY openssl.cnf ./

RUN /usr/bin/openssl req -x509 -newkey rsa:4096 \
    -keyout /etc/letsencrypt/live/example.org/privkey.pem \
    -out /etc/letsencrypt/live/example.org/fullchain.pem \
    -sha256 -days 365 -config openssl.cnf -nodes


